### ISSUE TITLE
the mysql functions used is obsolete!

### ISSUE THREAD

**Issue by chezsick** [ameer1234567890/sphider#2]
hello, the problem the functions using mysql on this repository is obsolete mysql_...() this is for php version 5
now, it's mysqli_...() for the php version 7

Thanks Sick.

**Comment by earthbound19** [comment]
https://github.com/compuphase/sphider-pdo
https://www.sphider-plus.eu/index.php?f=20

**Comment by ameer1234567890** [comment]
This only supports PHP5
